#.travis.yml

language: node_js
node_js:
  - "10.15"

os: darwin x64

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - yarn install

script:
  - ng e2e
  - ng build --prod